FaceDetector:
  detector_type: 1
  max_faces: 1
  fixed_window_size: 0
  threshold: 0.5
  sort_by: FaceSortBy.LARGEST
  temporal_smoothing: 1

FaceMarker:
  marker_type: 0
  marker_coverage: 1.1
  temporal_smoothing: 1

FrameAdjuster:
  median_blur_per: 0
  degrade_bicubic_per: 0

FaceAligner:
  face_coverage: 2.2
  resolution: 224
  exclude_moving_parts: True
  head_mode: False
  x_offset: 0.0
  y_offset: 0.0

FaceSwapper:
  dfs_model_path: C:/Users/zhenyuanshen/Downloads/DeepFaceLive_DirectX12/userdata/dfm_models/model_6000_SAEHD_model.dfm
#  dfs_model_stem: model_6000_SAEHD_model
  face_id: 0
  presharpen_amount: 0.0
  pre_gamma_red: 1.0
  pre_gamma_green: 1.0
  pre_gamma_blue: 1.0
  two_pass: False
  morph_factor: None

FaceMerger:
  face_x_offset: 0.0
  face_y_offset: 0.0
  face_scale: 1.0
  face_mask_type: 2
  face_mask_erode: 5
  face_mask_blur: 25
  face_opacity: 1.0